name: Build and Publish NuGet Package

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Push events to matching v*, e.g., v1.0, v20.15.10
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Copy README to project directory
      run: cp README.md src/YnDotNet/
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Set version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Set default version
      if: startsWith(github.ref, 'refs/tags/v') != true
      run: echo "PACKAGE_VERSION=1.0.0-preview-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
    - name: Pack
      run: dotnet pack --configuration Release --no-build -p:PackageVersion=$PACKAGE_VERSION -o out
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: out/*.nupkg
    
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json